// @ts-check
import { test, expect } from '@playwright/test';
import { LoginPage } from '../app/page/login-page';
import { ShopPage } from '../app/page/shop-page';
import { CartPage } from '../app/page/cart-page';
import { ProductCartPage } from '../app/page/product-cart-page';

test.describe('Login tests', () => {
  test('Login as standard user', async ({ page }) => {
    const loginPage = new LoginPage(page)
    //TODO:
    //Удалить shopPage так как он не используется в этом тесте
    const shopPage = new ShopPage(page)
    await loginPage.visit()
    await expect(loginPage.title).toHaveText('Swag Labs')
    await expect(loginPage.loginField).toHaveValue('')
    await expect(loginPage.passwordField).toHaveValue('')
    await loginPage.clickLoginButton()
    await expect(loginPage.errorField).toHaveText('Epic sadface: Username is required')
    //второй тест
    await loginPage.clickErrorFieldExitButton()
    await loginPage.setLoginField('standard_user')
    await expect(loginPage.loginField).toHaveValue('standard_user')
    await loginPage.clickLoginButton()
    await expect(loginPage.errorField).toHaveText('Epic sadface: Password is required')
    await loginPage.clickErrorFieldExitButton()
    await loginPage.clearLoginField()
    await expect(loginPage.loginField).toHaveValue('')
    await loginPage.setPasswordField('secret_sauce')
    await expect(loginPage.passwordField).toHaveValue('secret_sauce')
    await loginPage.clickLoginButton()
    await expect(loginPage.errorField).toHaveText('Epic sadface: Username is required')
    await loginPage.clickErrorFieldExitButton()
    await loginPage.clearPasswordField()
    await expect(loginPage.passwordField).toHaveValue('')
    await loginPage.setLoginField('standard_use')
    await expect(loginPage.loginField).toHaveValue('standard_use')
    await loginPage.setPasswordField('secret_sauce')
    await expect(loginPage.passwordField).toHaveValue('secret_sauce')
    await loginPage.clickLoginButton()
    await expect(loginPage.errorField).toHaveText('Epic sadface: Username and password do not match any user in this service')
    await loginPage.clickErrorFieldExitButton()
    await loginPage.clearLoginField()
    await expect(loginPage.loginField).toHaveValue('')
    await loginPage.clearPasswordField()
    await expect(loginPage.passwordField).toHaveValue('')
    await loginPage.setLoginField('standard_user')
    await expect(loginPage.loginField).toHaveValue('standard_user')
    await loginPage.setPasswordField('secret_sauc')
    await expect(loginPage.passwordField).toHaveValue('secret_sauc')
    await loginPage.clickLoginButton()
    await expect(loginPage.errorField).toHaveText('Epic sadface: Username and password do not match any user in this service')
    await loginPage.clickErrorFieldExitButton()
    await loginPage.clearLoginField()
    await expect(loginPage.loginField).toHaveValue('')
    await loginPage.clearPasswordField()
    await expect(loginPage.passwordField).toHaveValue('')
    await loginPage.setLoginField('standard_user')
    await expect(loginPage.loginField).toHaveValue('standard_user')
    await loginPage.setPasswordField('secret_sauce')
    await expect(loginPage.passwordField).toHaveValue('secret_sauce')
    await loginPage.clickLoginButton()
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
  });

  test('Products Check', async ({ page }) => {
    const loginPage = new LoginPage(page)
    const shopPage = new ShopPage(page)
    const cartPage = new CartPage(page)
    const productCartPage = new ProductCartPage(page)
    await loginPage.visit()
    await loginPage.setLoginField('standard_user')
    await expect(loginPage.loginField).toHaveValue('standard_user')
    //TODO:обязателшьно провенрка на висибл
    await loginPage.setPasswordField('secret_sauce')
    await expect(loginPage.passwordField).toHaveValue('secret_sauce')
    //TODO: обязателшьно провенрка на висибл
    await loginPage.clickLoginButton()
    await expect(shopPage.sectionProductsTitle).toHaveText('Products')
    await expect(shopPage.sectionProductsTitle).toBeVisible()
    await expect(shopPage.productsNames).toHaveText([
      "Sauce Labs Backpack",
      "Sauce Labs Bike Light",
      "Sauce Labs Bolt T-Shirt",
      "Sauce Labs Fleece Jacket",
      "Sauce Labs Onesie",
      "Test.allTheThings() T-Shirt (Red)"
    ])
    await shopPage.expectProductsToBeVisible()
    //TODO: Проверку на висибл через команду .all пример 

    await expect(shopPage.productsPrices).toHaveText([
      "$29.99",
      "$9.99",
      "$15.99",
      "$49.99",
      "$7.99",
      "$15.99"
    ])
    // Сделать преверку на висибл через команду .all пример как expectProductsToBeVisible
    //TODO: один товар добавлено и удаленно со страници
    await expect(shopPage.firstProductRemoveButton).toBeHidden()
    await shopPage.clickFirstProductAddToCartButton()
    await expect(shopPage.firstProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.firstProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await expect(shopPage.firstProductAddToCartButton).toBeHidden()
    await shopPage.clickFirstProductRemoveButton()
    await expect(shopPage.firstProductAddToCartButton).toHaveText('Add to cart')
    await expect(shopPage.firstProductAddToCartButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toBeHidden()
    await expect(shopPage.shoppingCartIcon).toBeVisible()
    //один товар добавлено и удаленно со страници корзины
    await expect(shopPage.firstProductRemoveButton).toBeHidden()
    await shopPage.clickFirstProductAddToCartButton()
    await expect(shopPage.firstProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.firstProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickShoppingCartIcon()
    await expect(page).toHaveURL('https://www.saucedemo.com/cart.html')
    await expect(cartPage.sectionYourCartTitle).toHaveText('Your Cart')
    await expect(cartPage.sectionYourCartTitle).toBeVisible()
    await expect(cartPage.sectionQTYTitle).toHaveText('QTY')
    await expect(cartPage.sectionQTYTitle).toBeVisible()
    await expect(cartPage.sectionDescriptionTitle).toHaveText('Description')
    await expect(cartPage.sectionDescriptionTitle).toBeVisible()
    await expect(cartPage.productsNames).toHaveText('Sauce Labs Backpack')
    await expect(cartPage.productsPrice).toHaveText('$29.99')
    await expect(cartPage.shoppingCartCountNumber).toHaveText('1')
    await expect(cartPage.shoppingCartCountNumber).toBeVisible()
    await cartPage.clickFirstProductRemoveButton()
    await expect(shopPage.shoppingCartCountNumber).toBeHidden()
    await expect(shopPage.shoppingCartIcon).toBeVisible()
    await cartPage.clickContinueShopping()
    //два товара добавить и удалить с сайта
    await expect(shopPage.firstProductRemoveButton).toBeHidden()
    await shopPage.clickFirstProductAddToCartButton()
    await expect(shopPage.firstProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.firstProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickSecondProductAddToCartButton()
    await expect(shopPage.secondProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.secondProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('2')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickFirstProductRemoveButton()
    await expect(shopPage.firstProductAddToCartButton).toHaveText('Add to cart')
    await expect(shopPage.firstProductAddToCartButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickSecondProductRemoveButton()
    await expect(shopPage.secondProductAddToCartButton).toHaveText('Add to cart')
    await expect(shopPage.secondProductAddToCartButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toBeHidden()
    await expect(shopPage.shoppingCartIcon).toBeVisible()
    //два товара добавить в корзину  и удалить с корзины
    await expect(shopPage.firstProductRemoveButton).toBeHidden()
    await shopPage.clickFirstProductAddToCartButton()
    await expect(shopPage.firstProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.firstProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickSecondProductAddToCartButton()
    await expect(shopPage.secondProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.secondProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('2')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickShoppingCartIcon()
    await expect(cartPage.productsNames).toHaveText([
      "Sauce Labs Backpack",
      "Sauce Labs Bike Light"
    ])
    await expect(cartPage.productsPrice).toHaveText([
      "$29.99",
      "$9.99"
    ])
    await expect(cartPage.shoppingCartCountNumber).toHaveText('2')
    await expect(cartPage.shoppingCartCountNumber).toBeVisible()
    await cartPage.clickFirstProductRemoveButton()
    await cartPage.clickSecondProductRemoveButton()
    await expect(shopPage.shoppingCartCountNumber).toBeHidden()
    await expect(shopPage.shoppingCartIcon).toBeVisible()
    await cartPage.clickContinueShopping()
    //6 товара добавить в корзину удалить 3 с корзины и удалить 2 с страницы
    await expect(shopPage.firstProductRemoveButton).toBeHidden()
    await shopPage.clickFirstProductAddToCartButton()
    await expect(shopPage.firstProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.firstProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickSecondProductAddToCartButton()
    await expect(shopPage.secondProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.secondProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('2')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickThirdProductAddToCartButton()
    await expect(shopPage.thirdProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.thirdProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('3')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickFourthProductAddToCartButton()
    await expect(shopPage.fourthProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.fourthProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('4')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickFifthProductAddToCartButton()
    await expect(shopPage.fifthProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.fifthProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('5')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickSixthProductAddToCartButton()
    await expect(shopPage.sixthProductRemoveButton).toHaveText('Remove')
    await expect(shopPage.sixthProductRemoveButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('6')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await shopPage.clickShoppingCartIcon()
    await expect(cartPage.productsNames).toHaveText(
      ["Sauce Labs Backpack",
        "Sauce Labs Bike Light",
        "Sauce Labs Bolt T-Shirt",
        "Sauce Labs Fleece Jacket",
        "Sauce Labs Onesie",
        "Test.allTheThings() T-Shirt (Red)"])
    await expect(cartPage.productsPrice).toHaveText([
      "$29.99",
      "$9.99",
      "$15.99",
      "$49.99",
      "$7.99",
      "$15.99"])
    await expect(cartPage.shoppingCartCountNumber).toHaveText('6')
    await expect(cartPage.shoppingCartCountNumber).toBeVisible()
    await cartPage.clickFirstProductRemoveButton()
    await cartPage.clickSecondProductRemoveButton()
    await cartPage.clickThirdProductRemoveButton()
    await cartPage.clickFourthProductRemoveButton()
    await expect(cartPage.shoppingCartCountNumber).toHaveText('2')
    await expect(cartPage.shoppingCartCountNumber).toBeVisible()
    await cartPage.clickContinueShopping()
    await expect(shopPage.fifthProductAddToCartButton).toBeHidden()
    await expect(shopPage.fifthProductRemoveButton).toHaveText('Remove')
    await shopPage.clickFifthProductRemoveButton()
    await expect(shopPage.fifthProductAddToCartButton).toHaveText('Add to cart')
    await expect(shopPage.fifthProductAddToCartButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toHaveText('1')
    await expect(shopPage.shoppingCartCountNumber).toBeVisible()
    await expect(shopPage.sixthProductAddToCartButton).toBeHidden()
    await expect(shopPage.sixthProductRemoveButton).toHaveText('Remove')
    await shopPage.clickSixthProductRemoveButton()
    await expect(shopPage.sixthProductAddToCartButton).toHaveText('Add to cart')
    await expect(shopPage.sixthProductAddToCartButton).toBeVisible()
    await expect(shopPage.shoppingCartCountNumber).toBeHidden()
    await expect(shopPage.shoppingCartIcon).toBeVisible()
    // A → Z (по умолчанию)
    await expect(shopPage.filter).toBeVisible()
    await expect(shopPage.activeFilter).toHaveText('Name (A to Z)')
    await expect(shopPage.filter).toHaveValue('az')
    await shopPage.expectProductsSortedAToZ()
    // Z → A
    await shopPage.selectFilter('za')
    await expect(shopPage.activeFilter).toHaveText('Name (Z to A)')
    await expect(shopPage.filter).toHaveValue('za')
    await shopPage.expectProductsSortedZToA()
    // Price low → high
    await shopPage.selectFilter('lohi')
    await expect(shopPage.activeFilter).toHaveText('Price (low to high)')
    await expect(shopPage.filter).toHaveValue('lohi')
    await shopPage.expectProductsSortedLowToHigh()
    // Price high → low
    await shopPage.selectFilter('hilo')
    await expect(shopPage.activeFilter).toHaveText('Price (high to low)')
    await expect(shopPage.filter).toHaveValue('hilo')
    await shopPage.expectProductsSortedHighToLow()
    // Вернуть обратно A → Z
    await shopPage.selectFilter('az')
    await expect(shopPage.activeFilter).toHaveText('Name (A to Z)')
    await expect(shopPage.filter).toHaveValue('az')
    await shopPage.expectProductsSortedAToZ()
    await expect(shopPage.burgerMenuButton).toBeVisible()
    await shopPage.clickBurgerMenuButton()
    await expect(shopPage.allIteams).toHaveText('All Items')
    await expect(shopPage.about).toHaveText('About')
    await expect(shopPage.logout).toHaveText('Logout')
    await expect(shopPage.resetAppState).toHaveText('Reset App State')
    await expect(shopPage.burgerMenuCrossButton).toBeVisible()
    await shopPage.clickBurgerMenuCrossButton()
    await expect(shopPage.burgerMenuList).toBeHidden()
    //проверка карты товара
    await shopPage.openProductByName('Sauce Labs Backpack')
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory-item.html?id=4')
    await expect(productCartPage.productName).toHaveText('Sauce Labs Backpack')
    await expect(productCartPage.productName).toBeVisible()
    await expect(productCartPage.productImage).toBeVisible()
    await expect(productCartPage.productText).toHaveText('carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.')
    await expect(productCartPage.productText).toBeVisible()
    await expect(productCartPage.productPrice).toHaveText('$29.99')
    await expect(productCartPage.productPrice).toBeVisible()
    await expect(productCartPage.addToCartButton).toHaveText('Add to cart')
    await expect(productCartPage.addToCartButton).toBeVisible()
    await expect(productCartPage.removeButton).toBeHidden()
    await productCartPage.clickAddToCartButton()
    await expect(productCartPage.removeButton).toHaveText('Remove')
    await expect(productCartPage.removeButton).toBeVisible()
    await expect(productCartPage.shoppingCartCountNumber).toHaveText('1')
    await expect(productCartPage.shoppingCartCountNumber).toBeVisible()
    await productCartPage.clickRemoveButton()
    await expect(productCartPage.addToCartButton).toHaveText('Add to cart')
    await expect(productCartPage.addToCartButton).toBeVisible()
    await expect(productCartPage.shoppingCartCountNumber).toBeHidden()
    await expect(productCartPage.shoppingCartIcon).toBeVisible()
    await expect(productCartPage.backToProduct).toHaveText('Back to products')
    await expect(productCartPage.backToProduct).toBeVisible()
    await expect(productCartPage.backToProductIcon).toBeVisible()
    await productCartPage.clickBackToProducts()
    //проверка ол айтемс
    await shopPage.openProductByName('Sauce Labs Backpack')
    await shopPage.clickBurgerMenuButton()
    await (shopPage.allIteams).click()
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
    await shopPage.clickBurgerMenuButton()
    await (shopPage.logout).click()
    await expect(page).toHaveURL('https://www.saucedemo.com/')
     await loginPage.setLoginField('standard_user')
    await loginPage.setPasswordField('secret_sauce')
    await loginPage.clickLoginButton()
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
    await shopPage.clickBurgerMenuButton()
    await (shopPage.about).click()
    await expect(page).toHaveURL('https://saucelabs.com/')
  });
});